version: '3.1'

services:

  mysql:
    image: mariadb:10.11
    container_name: mysql
    restart: unless-stopped
    command: ['mysqld','--character-set-server=utf8mb4']
    volumes:
      - databasevolume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      
  openemr:
    image: openemr/openemr:7.0.2
    container_name: openemr
    restart: unless-stopped
    ports:
      - "8200:80"
      - "8443:443"
    volumes:
      - htdocs:/var/www/localhost/htdocs/openemr/:rw
    environment:
      MYSQL_HOST: mysql
      MYSQL_ROOT_PASS: root
      MYSQL_USER: openemr
      MYSQL_PASS: openemr
      OE_USER: admin
      OE_PASS: pass
    depends_on:
      - mysql
      
  phpmyadmin:
    image: phpmyadmin
    container_name: pma-openemr    
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      - PMA_HOSTS=mysql
      
volumes:
  htdocs: {}
  databasevolume: {}
