version: '3.3'

services:

    openemr:
        image: openemr/openemr
        container_name: openemr
        ports:
            - "8200:80"
            - "8243:443"
        restart: unless-stopped
        volumes:
            - ./log_volume:/var/log
            - ./site_volume:/var/www/localhost/htdocs/openemr/sites
        environment:
            - MYSQL_HOST=mysql
            - MYSQL_ROOT_PASS=root
            - MYSQL_USER=openemr
            - MYSQL_PASS=openemr
            - MYSQL_DATABASE=openemr
            - OE_USER=admin
            - OE_PASS=pass
        depends_on:
            - mysql
        networks:
            - mynet

services:

    mysql:
        image: mariadb
        container_name: mysql
 #       command: --character-set-server=utf8
        command: ['mysqld','--character-set-server=utf8mb4']
        restart: unless-stopped
        volumes:
            - ./db_volume:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
        networks:
            - mynet

services:
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        ports:
            - "8080:80"
        restart: unless-stopped
        environment:
            - PMA_HOST=mysql
        networks:
            - mynet





